
export db_name='online_library'
export host_name='localhost'
export host_port='5432'
export db_username='libuser'
export db_password='libpass'
export app_host='0.0.0.0'
export app_port='8000'
export token_expiration_interval='6000'
export new_token_request_valid_interval='30'
export save_path=/home/nsm/PycharmProjects/online_library/pictures
export log_path=/home/nsm/PycharmProjects/online_library/logs/app.log
export redis_host='localhost'
export valid_registering_intervall=60
export valid_activating_intervall=86400
export reset_password_interval=120
export admin_username='admin'
export sms_api_key='51493c0cc42cd23559c73c0c'
export sms_security_key='Jame_jam@nsm5msd&*!'
export sms_token_url='https://RestfulSms.com/api/Token'
export sms_send_url='https://RestfulSms.com/api/MessageSend'
export sms_line_no='10005195'
export sms_sender='کتابخوان جام جم'
export sms_timeout=20
export permission_list_expiration_time=60
export app_server_address ='http://localhost:7000'
export kipo_merchant_key='09082001359'