"""some fields in person changed

Revision ID: 0c85d49a5e63
Revises: b8fd6cb54013
Create Date: 2019-06-17 14:09:22.696602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c85d49a5e63'
down_revision = 'b8fd6cb54013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_roles_preson_id_fkey', 'book_roles', type_='foreignkey')
    op.drop_column('book_roles', 'preson_id')
    op.add_column('presons', sa.Column('address', sa.String(), nullable=True))
    op.add_column('presons', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('presons', 'addresses')
    op.drop_column('presons', 'phones')
    op.drop_constraint('users_person_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'person_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('person_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_person_id_fkey', 'users', 'presons', ['person_id'], ['id'])
    op.add_column('presons', sa.Column('phones', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('presons', sa.Column('addresses', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('presons', 'phone')
    op.drop_column('presons', 'address')
    op.add_column('book_roles', sa.Column('preson_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('book_roles_preson_id_fkey', 'book_roles', 'presons', ['preson_id'], ['id'])
    # ### end Alembic commands ###
