"""current_book and status added to person and library

Revision ID: 0df0a350be44
Revises: 4194b9ee7aa1
Create Date: 2019-07-06 13:04:04.585400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0df0a350be44'
down_revision = '4194b9ee7aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('status', sa.JSON(), nullable=True))
    op.add_column('persons', sa.Column('current_book', postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'current_book')
    op.drop_column('library', 'status')
    # ### end Alembic commands ###
