"""collection table alterde3

Revision ID: 204ad92f2403
Revises: 6701c8c1e6fe
Create Date: 2019-08-25 15:07:14.664169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '204ad92f2403'
down_revision = '6701c8c1e6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('book_id', sa.ARRAY(postgresql.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'book_id')
    # ### end Alembic commands ###
