"""library added to book module

Revision ID: 27387eff89b4
Revises: 4473e6dd7e1d
Create Date: 2019-06-16 11:49:41.474577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27387eff89b4'
down_revision = '4473e6dd7e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book_roles', ['id'])
    op.create_unique_constraint(None, 'books', ['id'])
    op.create_unique_constraint(None, 'constraints', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'presons', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'presons', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'constraints', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'book_roles', type_='unique')
    # ### end Alembic commands ###
