"""dynamic loading omitted from book_roles and library

Revision ID: 28896acd17eb
Revises: 2b600c59e81c
Create Date: 2019-06-25 12:51:34.813556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28896acd17eb'
down_revision = '2b600c59e81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
