"""tag added to primary model

Revision ID: 2a8dd0d5afc1
Revises: 5dc6b49b1ab2
Create Date: 2019-05-28 11:11:37.931369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8dd0d5afc1'
down_revision = '5dc6b49b1ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
