"""genre in book changed

Revision ID: 3035567744cb
Revises: 80047b60ec81
Create Date: 2019-07-01 15:26:45.592426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3035567744cb'
down_revision = '80047b60ec81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', postgresql.ENUM('Comedy', 'Drama', 'Romance', 'Social', 'Religious', 'Historical', name='genre'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
