"""comment-actions model added--3

Revision ID: 34ad0202fc10
Revises: bb841c87160b
Create Date: 2019-07-17 19:27:00.556862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ad0202fc10'
down_revision = 'bb841c87160b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_actions', sa.Column('like', sa.BOOLEAN(), nullable=True))
    op.create_unique_constraint(None, 'comment_actions', ['id'])
    op.drop_column('comment_actions', 'helpful')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_actions', sa.Column('helpful', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment_actions', type_='unique')
    op.drop_column('comment_actions', 'like')
    # ### end Alembic commands ###
