"""progress added to library

Revision ID: 3790bfefc97f
Revises: 4c459ce0c059
Create Date: 2019-10-26 18:28:39.101151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3790bfefc97f'
down_revision = '4c459ce0c059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_seens',
    sa.Column('creation_date', sa.Integer(), nullable=False),
    sa.Column('modification_date', sa.Integer(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('modifier', sa.String(), nullable=True),
    sa.Column('sender_id', postgresql.UUID(), nullable=False),
    sa.Column('receptor_id', postgresql.UUID(), nullable=True),
    sa.Column('group_id', postgresql.UUID(), nullable=True),
    sa.Column('last_seen', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['discussion_groups.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'chat_messages', ['id'])
    op.add_column('library', sa.Column('progress', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'progress')
    op.drop_constraint(None, 'chat_messages', type_='unique')
    op.drop_table('last_seens')
    # ### end Alembic commands ###
