"""book details added to book and person.bio

Revision ID: 3a55433ca46a
Revises: 7f36df32fe2c
Create Date: 2019-07-15 14:53:40.044475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a55433ca46a'
down_revision = 'f8e7bfd33267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('books', sa.Column('isben', sa.String(), nullable=True))
    op.add_column('books', sa.Column('pages', sa.String(), nullable=True))
    op.add_column('books', sa.Column('size', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('follower_list', postgresql.ARRAY(postgresql.UUID()), nullable=True))
    op.add_column('persons', sa.Column('following_list', postgresql.ARRAY(postgresql.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'following_list')
    op.drop_column('persons', 'follower_list')
    op.drop_column('persons', 'bio')
    op.drop_column('books', 'size')
    op.drop_column('books', 'pages')
    op.drop_column('books', 'isben')
    op.drop_column('books', 'duration')
    # ### end Alembic commands ###
