"""unique cons added to connector

Revision ID: 4399d017d8ad
Revises: 112939a9c20a
Create Date: 2019-09-01 12:44:22.791775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4399d017d8ad'
down_revision = '112939a9c20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_entity_connector_UniqueCode_key', 'unique_entity_connector', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_entity_connector_UniqueCode_key', 'unique_entity_connector', ['UniqueCode'])
    # ### end Alembic commands ###
