"""user_id deleted to persons

Revision ID: 485d8bdb8738
Revises: d81349db17d3
Create Date: 2019-06-19 14:20:27.592331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '485d8bdb8738'
down_revision = 'd81349db17d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
