"""order and order_item added to db

Revision ID: 4e258ec6af1c
Revises: 5430b3b87de2
Create Date: 2019-07-30 12:24:42.929481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e258ec6af1c'
down_revision = '5430b3b87de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('creation_date', sa.Integer(), nullable=False),
    sa.Column('modification_date', sa.Integer(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('modifier', sa.String(), nullable=True),
    sa.Column('order_id', postgresql.UUID(), nullable=False),
    sa.Column('book_id', postgresql.UUID(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('net_price', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('orders', sa.Column('description', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('price_detail', sa.JSON(), nullable=True))
    op.drop_constraint('prices_book_id_key', 'prices', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('prices_book_id_key', 'prices', ['book_id'])
    op.drop_column('orders', 'price_detail')
    op.drop_column('orders', 'description')
    op.drop_table('order_items')
    # ### end Alembic commands ###
