"""changes in book_rate happend to have default zero

Revision ID: 55d48ed26fe9
Revises: 1a0dc77a1fed
Create Date: 2019-07-22 11:37:07.560655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d48ed26fe9'
down_revision = '1a0dc77a1fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'collections', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='unique')
    # ### end Alembic commands ###
