"""unique table altered

Revision ID: 56b78d71b550
Revises: a3b3da8991b8
Create Date: 2019-09-01 22:56:42.150361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b78d71b550'
down_revision = 'a3b3da8991b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_entity_connector_entity_id_key', 'unique_entity_connector', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_entity_connector_entity_id_key', 'unique_entity_connector', ['entity_id'])
    # ### end Alembic commands ###
