"""comment

Revision ID: 58b9bbc481b3
Revises: a7d2d41f6f29
Create Date: 2019-06-03 10:30:28.211995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b9bbc481b3'
down_revision = 'a7d2d41f6f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
