"""user -- add field full_name

Revision ID: 59df3803ae09
Revises: e9b055927fec
Create Date: 2019-11-09 14:57:41.802259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59df3803ae09'
down_revision = 'e9b055927fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'full_name')
    # ### end Alembic commands ###
