"""book--press fileld added

Revision ID: 602265aff076
Revises: 54f888931815
Create Date: 2019-10-09 13:31:20.717039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '602265aff076'
down_revision = '54f888931815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('press', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'books', 'persons', ['press'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'press')
    # ### end Alembic commands ###
