"""collection table again back to 3 migrate prior2

Revision ID: 690ec24ff365
Revises: ab90dacbf303
Create Date: 2019-08-26 13:37:09.793109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '690ec24ff365'
down_revision = 'ab90dacbf303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('book_id', postgresql.UUID()))
    op.create_foreign_key(None, 'collections', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_column('collections', 'book_id')
    # ### end Alembic commands ###
