"""unique_entitiy_connector added

Revision ID: 7416539768d7
Revises: 337fd52a66a8
Create Date: 2019-08-27 14:27:51.236632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7416539768d7'
down_revision = '337fd52a66a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'unique_entity_connector', ['id'])
    op.create_unique_constraint(None, 'unique_entity_connector', ['entity_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unique_entity_connector', type_='unique')
    op.drop_constraint(None, 'unique_entity_connector', type_='unique')
    # ### end Alembic commands ###
