"""comment

Revision ID: 773120adc63f
Revises: 58b9bbc481b3
Create Date: 2019-06-03 10:39:37.441533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '773120adc63f'
down_revision = '58b9bbc481b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('creation_date', sa.Integer(), nullable=False),
    sa.Column('modification_date', sa.Integer(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('edition', sa.Integer(), nullable=True),
    sa.Column('press', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('translator', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('editors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('narrators', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pub_year', sa.Integer(), nullable=True),
    sa.Column('types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
