"""person current_book field name changed

Revision ID: 7f36df32fe2c
Revises: 0df0a350be44
Create Date: 2019-07-07 12:11:26.297830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f36df32fe2c'
down_revision = '0df0a350be44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('current_book_id', postgresql.UUID(), nullable=True))
    op.drop_column('persons', 'current_book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('current_book', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_column('persons', 'current_book_id')
    # ### end Alembic commands ###
