"""genre in book changed

Revision ID: 80047b60ec81
Revises: 28896acd17eb
Create Date: 2019-07-01 15:16:14.320771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80047b60ec81'
down_revision = '28896acd17eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
