"""library entity changed

Revision ID: 8b8a552d9d24
Revises: 4e258ec6af1c
Create Date: 2019-07-30 15:28:22.819879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b8a552d9d24'
down_revision = '4e258ec6af1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices',
                  sa.Column('book_id', postgresql.UUID(), nullable=False))
    op.create_unique_constraint(None, 'prices', ['book_id'])
    op.create_unique_constraint(None, 'prices', ['id'])
    op.create_foreign_key(None, 'prices', 'books', ['book_id'], ['id'])
    op.add_column('library', sa.Column('person_id', postgresql.UUID(), nullable=False))
    op.drop_constraint('library_user_id_fkey', 'library', type_='foreignkey')
    op.create_foreign_key(None, 'library', 'persons', ['person_id'], ['id'])
    op.drop_column('library', 'user_id')
    op.create_unique_constraint(None, 'order_items', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='unique')
    op.add_column('library', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.create_foreign_key('library_user_id_fkey', 'library', 'users', ['user_id'], ['id'])
    op.drop_column('library', 'person_id')
    # ### end Alembic commands ###
