"""collection table alterde

Revision ID: 9a2b66d9400c
Revises: 8b8a552d9d24
Create Date: 2019-08-25 14:54:32.698157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2b66d9400c'
down_revision = '8b8a552d9d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
