"""unique table altered

Revision ID: a3b3da8991b8
Revises: 4399d017d8ad
Create Date: 2019-09-01 22:54:08.090451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b3da8991b8'
down_revision = '4399d017d8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'unique_entity_connector', ['UniqueCode', 'entity_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unique_entity_connector', type_='unique')
    # ### end Alembic commands ###
