"""collection table again back to 3 migrate prior

Revision ID: ab90dacbf303
Revises: 204ad92f2403
Create Date: 2019-08-26 13:35:36.965195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab90dacbf303'
down_revision = '204ad92f2403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('book_id', postgresql.ARRAY(postgresql.UUID()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
