"""unque constraint added to persons cell_no

Revision ID: af39ff2de317
Revises: 806ef17af6eb
Create Date: 2019-06-18 09:13:03.955081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af39ff2de317'
down_revision = '806ef17af6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persons', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'persons', ['email'])
    op.create_unique_constraint(None, 'persons', ['image'])
    op.create_unique_constraint(None, 'persons', ['cell_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persons', type_='unique')
    op.drop_constraint(None, 'persons', type_='unique')
    op.drop_constraint(None, 'persons', type_='unique')
    op.alter_column('persons', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
