"""payment details addedto transaction

Revision ID: b8f679b6ef0d
Revises: 585ba4a0bf50
Create Date: 2019-11-06 21:53:22.643567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f679b6ef0d'
down_revision = '585ba4a0bf50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payments', ['id'])
    op.add_column('transactions', sa.Column('payment_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_details')
    op.drop_constraint(None, 'payments', type_='unique')
    # ### end Alembic commands ###
