"""removed library relation from user

Revision ID: b8fd6cb54013
Revises: b956f59b0557
Create Date: 2019-06-16 12:18:25.925640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8fd6cb54013'
down_revision = 'b956f59b0557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
