"""removing unique constraints on library

Revision ID: b956f59b0557
Revises: c40db208c708
Create Date: 2019-06-16 11:54:16.336411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b956f59b0557'
down_revision = 'c40db208c708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('library_book_id_user_id_key', 'library', type_='unique')
    op.create_unique_constraint(None, 'library', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'library', type_='unique')
    op.create_unique_constraint('library_book_id_user_id_key', 'library', ['book_id', 'user_id'])
    # ### end Alembic commands ###
