"""prices added to database--book_id in lowercase

Revision ID: cce5582bdca1
Revises: 54bf90de4c0f
Create Date: 2019-07-23 15:07:50.647449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cce5582bdca1'
down_revision = '54bf90de4c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prices_Book_id_key', 'prices', type_='unique')
    op.drop_column('prices', 'Book_id')
    op.add_column('prices', sa.Column('book_id', postgresql.UUID(), nullable=False))
    op.create_unique_constraint(None, 'prices', ['book_id'])
    op.create_unique_constraint(None, 'prices', ['id'])
    op.drop_constraint('prices_Book_id_fkey', 'prices', type_='foreignkey')
    op.create_foreign_key(None, 'prices', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('Book_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.create_foreign_key('prices_Book_id_fkey', 'prices', 'books', ['Book_id'], ['id'])
    op.drop_constraint(None, 'prices', type_='unique')
    op.drop_constraint(None, 'prices', type_='unique')
    op.create_unique_constraint('prices_Book_id_key', 'prices', ['Book_id'])
    op.drop_column('prices', 'book_id')
    # ### end Alembic commands ###
