"""email in person can be none

Revision ID: ce77d7a00c62
Revises: ee6a6ebc1ec0
Create Date: 2019-06-24 19:08:26.589535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce77d7a00c62'
down_revision = 'ee6a6ebc1ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
