"""status filed addecto payment

Revision ID: d0b10351e471
Revises: b8f679b6ef0d
Create Date: 2019-11-09 11:33:16.468639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b10351e471'
down_revision = 'b8f679b6ef0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'status')
    # ### end Alembic commands ###
