"""user_id added to persons

Revision ID: d81349db17d3
Revises: af39ff2de317
Create Date: 2019-06-19 14:12:09.955984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd81349db17d3'
down_revision = 'af39ff2de317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('user_id', postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'user_id')
    # ### end Alembic commands ###
