"""Base extends Mongosql now!

Revision ID: e43690dc1811
Revises: 59df3803ae09
Create Date: 2019-11-10 12:38:31.908366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43690dc1811'
down_revision = '59df3803ae09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('constraints_UniqueCode_key', 'constraints', type_='unique')
    op.drop_constraint('discussion_members_id_key', 'discussion_members', type_='unique')
    op.create_unique_constraint(op.f('discussion_members_id_key'), 'discussion_members', ['group_id', 'person_id'])
    op.drop_constraint('discussion_members_group_id_person_id_key', 'discussion_members', type_='unique')
    op.drop_constraint('group_permissions_id_key', 'group_permissions', type_='unique')
    op.create_unique_constraint(op.f('group_permissions_id_key'), 'group_permissions', ['group_id', 'permission_id'])
    op.drop_constraint('group_permissions_group_id_permission_id_key', 'group_permissions', type_='unique')
    op.drop_constraint('group_users_group_id_user_id_key', 'group_users', type_='unique')
    op.drop_constraint('groups_title_key', 'groups', type_='unique')
    op.drop_constraint('permissions_id_key', 'permissions', type_='unique')
    op.create_unique_constraint(op.f('permissions_id_key'), 'permissions', ['permission'])
    op.drop_constraint('permissions_permission_key', 'permissions', type_='unique')
    op.drop_constraint('persons_cell_no_key', 'persons', type_='unique')
    op.drop_constraint('persons_email_key', 'persons', type_='unique')
    op.drop_constraint('prices_book_id_key', 'prices', type_='unique')
    op.drop_constraint('unique_entity_connector_UniqueCode_entity_id_key', 'unique_entity_connector', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('unique_entity_connector_UniqueCode_entity_id_key', 'unique_entity_connector', ['UniqueCode', 'entity_id'])
    op.create_unique_constraint('prices_book_id_key', 'prices', ['book_id'])
    op.create_unique_constraint('persons_email_key', 'persons', ['email'])
    op.create_unique_constraint('persons_cell_no_key', 'persons', ['cell_no'])
    op.create_unique_constraint('permissions_permission_key', 'permissions', ['permission'])
    op.drop_constraint(op.f('permissions_id_key'), 'permissions', type_='unique')
    op.create_unique_constraint('permissions_id_key', 'permissions', ['id'])
    op.create_unique_constraint('groups_title_key', 'groups', ['title'])
    op.create_unique_constraint('group_users_group_id_user_id_key', 'group_users', ['group_id', 'user_id'])
    op.create_unique_constraint('group_permissions_group_id_permission_id_key', 'group_permissions', ['group_id', 'permission_id'])
    op.drop_constraint(op.f('group_permissions_id_key'), 'group_permissions', type_='unique')
    op.create_unique_constraint('group_permissions_id_key', 'group_permissions', ['id'])
    op.create_unique_constraint('discussion_members_group_id_person_id_key', 'discussion_members', ['group_id', 'person_id'])
    op.drop_constraint(op.f('discussion_members_id_key'), 'discussion_members', type_='unique')
    op.create_unique_constraint('discussion_members_id_key', 'discussion_members', ['id'])
    op.create_unique_constraint('constraints_UniqueCode_key', 'constraints', ['UniqueCode'])
    # ### end Alembic commands ###
