"""unique connector changed

Revision ID: e58715438c77
Revises: 709e75ace9e7
Create Date: 2019-08-31 16:50:08.955090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58715438c77'
down_revision = '709e75ace9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'collections', ['title', 'person_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='unique')
    # ### end Alembic commands ###
