"""deleted library from books

Revision ID: e899b0642527
Revises: 55d48ed26fe9
Create Date: 2019-07-22 13:38:07.705091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e899b0642527'
down_revision = '55d48ed26fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('creation_date', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('book_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='library_book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='library_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='library_pkey'),
    sa.UniqueConstraint('id', name='library_id_key')
    )
    # ### end Alembic commands ###
