"""payment_id added to transaction

Revision ID: e9b055927fec
Revises: d0b10351e471
Create Date: 2019-11-09 13:57:08.002247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9b055927fec'
down_revision = 'd0b10351e471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('details', sa.JSON(), nullable=True))
    op.add_column('transactions', sa.Column('payment_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'payments', ['payment_id'], ['id'])
    op.drop_column('transactions', 'payment_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'payment_id')
    op.drop_column('transactions', 'details')
    # ### end Alembic commands ###
