"""person table altered

Revision ID: ee6a6ebc1ec0
Revises: 485d8bdb8738
Create Date: 2019-06-24 18:25:08.414723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6a6ebc1ec0'
down_revision = '485d8bdb8738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('persons_image_key', 'persons', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('persons_image_key', 'persons', ['image'])
    # ### end Alembic commands ###
