"""user controller and token added to project

Revision ID: eec76ea91ddd
Revises: 773120adc63f
Create Date: 2019-06-03 12:17:55.314705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec76ea91ddd'
down_revision = '773120adc63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('creator', sa.String(), nullable=True))
    op.add_column('books', sa.Column('modifier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('creator', sa.String(), nullable=True))
    op.add_column('users', sa.Column('modifier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modifier')
    op.drop_column('users', 'creator')
    op.drop_column('books', 'modifier')
    op.drop_column('books', 'creator')
    # ### end Alembic commands ###
