"""initial migrate1

Revision ID: feb2867a21cd
Revises: faf3a7b5a0cc
Create Date: 2019-05-27 22:31:56.008853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb2867a21cd'
down_revision = 'faf3a7b5a0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('username', name='users_pkey')
    )
    # ### end Alembic commands ###
